version: "3.1"
services:
  web:
    build:
      context: ./
      dockerfile: app/Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    volumes: 
      - ./switches.json:/switches.json
      - ./users.json:/users.json
      - ./config.json:/config.json